### ISSUE TITLE
does not have access to window.location.hash changing

### ISSUE THREAD

**Issue by gabrielcsapo** [rstacruz/mocha-jsdom#15]
```
it('should trigger window.location to be the value of the hash', function() {
	window.location.hash = home;
	console.log(window.location.hash); // (nothing)
});
```

**Comment by rstacruz** [comment]
this is likely a jsdom issue.

**Comment by rstacruz** [comment]
...in jsdom, i think location.hash needs to start with a `#`, like so:

```js
window.location.hash = '#top'
console.log(window.location.hash) // '#top'
```

**Comment by gabrielcsapo** [comment]
@rstacruz so this is the intended behavior is to not accept values that don't have a hash in front of the string?

**Comment by rstacruz** [comment]
I'm not one of the developers of jsdom to comment on the issue, so I can't answer authoritatively on this.

It does seem like a reasonable limitation to me, though... I vaguely recall maybe some older versions of some browsers behaved that way.

**Comment by rstacruz** [comment]
Let me also add that you can raise this concern over at [tmpvar/jsdom](https://github.com/tmpvar/jsdom).

**Comment by rstacruz** [comment]
Okay, I just tried it out and it doesn't seem to work at all, `#` or not...

![image](https://cloud.githubusercontent.com/assets/74385/14751456/87bdea7e-08fc-11e6-8d9c-76db609aa44c.png)

https://github.com/tmpvar/jsdom/issues/1300
