### ISSUE TITLE
Timeout issue?

### ISSUE THREAD

**Issue by Nic128** [rstacruz/mocha-jsdom#17]
I am running 2 tests with similar code.

````
let jsdom = require('mocha-jsdom');
describe('Field TextInput component', () => {
  jsdom();
  ...
});
````

I have a timeout issue that doesn't happen locally, but when using a slower build machine it sometimes happen. I don't use any `before` statements in those tests. The error points to mocha-jsdom and I'm wondering why. It is probably environment related. Maybe you could help me where to look .

````
1) Field TextInput component "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at node_modules/jsdom/lib/jsdom.js:271:18
````

I'm wondering what could be the issue?

**Comment by rstacruz** [comment]
How about running mocha with --timeout 20000?

Rico Sta. Cruz  ·  ricostacruz.com  ·  @rstacruz

On January 5, 2016 at 4:23:25 AM, Nic128 (notifications@github.com) wrote:

I am running 2 tests with similar code

let jsdom = require('mocha-jsdom');
describe('Field TextInput component', () => {
  jsdom();

});

I have a timeout issue that doesn't happen locally, but when using a slower build machine it sometimes happen I don't use any before statements in those tests The error points to mocha-jsdom and I'm wondering why It is probably environment related Maybe you could help me where to look

1) Field TextInput component "before all" hook:
     Error: timeout of 2000ms exceeded Ensure the done() callback is being called in this test
      at Objectdone (node_modules/mocha-jsdom/indexjs:70:7)
      at node_modules/jsdom/lib/jsdomjs:271:18

I'm wondering what could be the issue?

**Comment by Nic128** [comment]
Yep, it works constantly now. Thanks.

**Comment by Skahrz** [comment]
I have the same issue. Any solution ?

**Comment by rstacruz** [comment]
Either:

a. Use `mocha --timeout 20000`
b. Add `--timeout 20000` to `test/mocha.opts`

Alternatively, use https://github.com/rstacruz/jsdom-global instead, which is considered to be mocha-jsdom's successor.

**Comment by alex-hutton** [comment]
> Alternatively, use https://github.com/rstacruz/jsdom-global instead, which is considered to be mocha-jsdom's successor.

If `mocha-global` is the successor, why does it appear that `mocha-jsdom` is still being maintained (most recent commit March 26, 2019), whereas `jsdom-global` is no longer being maintained (most recent commit, May 8, 2017)
