### ISSUE TITLE
In react, it still complains that 'window' or 'document' are not available globally

### ISSUE THREAD

**Issue by ZhengHe-MD** [rstacruz/mocha-jsdom#24]
Invariant Violation: dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use ReactDOMServer.renderToString() for server rendering.

part of my code

```
import 'babel-polyfill';
import jsdom from 'mocha-jsdom';
import React from 'react';
import expect from 'expect';
import expectJSX from 'expect-jsx';
import { shallow, mount } from 'enzyme';
import { createRenderer } from 'react-addons-test-utils';
import MDFlashMessage from 'src/MDFlashMessage';

expect.extend(expectJSX);

describe('MDFlashMessage', () => {

  jsdom();
  ...
  it('should render null after given duration', async () => {
      const wrapper = mount(<MDFlashMessage timeout={1000} />);
      await setTimeout(() => {
        const hidden = wrapper.state().hidden;
        expect(hidden).toBe(true);
      }, 2000);
   });
}
```

note that it first

**Comment by rstacruz** [comment]
try using it this way instead:

```js
import jsdom from 'mocha-jsdom/register'
```

maybe React needs to have the DOM present right away at the point of it being `import`/`require`d.

**Comment by rstacruz** [comment]
try using jsdom-global instead:

```js
import 'jsdom-global/register'
```

maybe React needs to have the DOM present right away at the point of it being `import`/`require`d.

https://www.npmjs.com/package/jsdom-global
