### ISSUE TITLE
ESLint advocates requires in the global context, jquery example violates that best practice

### ISSUE THREAD

**Issue by anselmbradford** [rstacruz/mocha-jsdom#9]
See http://eslint.org/docs/rules/global-require.html

If a test file uses the `require` for jquery in the `before` the above rule doesn't pass.
What's the guidance if you wanted to lint the test files with that rule enabled? Is ignoring the rule the only option?

**Comment by rstacruz** [comment]
i suppose that's a good idea.

there's also `rerequire`: https://github.com/rstacruz/mocha-jsdom#working-with-mocha---watch
